//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoPark.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dogovor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dogovor()
        {
            this.Cars = new HashSet<Cars>();
        }
    
        public int Id { get; set; }
        public string FIO { get; set; }
        public string Age { get; set; }
        public string Passport { get; set; }
        public string DriverLicense { get; set; }
        public string Phone { get; set; }
        public string DateVidachi { get; set; }
        public string DateVozvrat { get; set; }
        public string Count { get; set; }
        public string Zalog { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cars> Cars { get; set; }
    }
}
